config/routes.rb
Rails.application.routes.draw do

  #加入認證
  post 'auth_user' => 'authentication#authenticate_user'

  apipie
  devise_for :users
  root "products#index"
  resources :products,  only: [:index, :show, :new, :create]

  resource :cart, only: [:show, :destroy] do
    post :add, path: '/add/:id'
    get :checkout
  end

  resources :orders, only: [:index, :show, :new, :create] do
	  	member do
	  	delete :cancel
	  end
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :order_items




  include AASM
  aasm do
    state :pending, initial: true
    state :paid, :shipped, :delivered, :cancelled

    event :pay do
      transitions from: :pending, to: :paid

      after do
        # 發送簡訊
      end
    end

    event :ship do
      transitions from: :paid, to: :shipped

      after do
        # 發送 line 訊息
        puts "心存善念"
      end
    end

    event :deliver do
      transitions from: :shipped, to: :delivered
    end

    event :cancel do
      transitions from: [:pending, :delivered], to: :cancelled
    end
  end  

  def total_price
  	order_items.reduce(0) { |sum, item| sum + item.price }
  end

  
  def serial
  	# "00000000#{id}".right(8)
  	"OD#{id.to_s.rjust(8,"0")}" #兩種都可以寫

  end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :user_only!, only: [:create, :index, :cancel, :show]

  def index
  	@orders = current_user.orders #以使用者角度
  end

  def show
    @order = current_user.orders.find_by(id: params[:id])
    redirect_to orders_path, alert: "查無此訂單" unless @order
  end


  def cancel
  	# order = Order.find_by(id: params[:id],user_id: current_user.id)
    order = current_user.orders.find_by(id: params[:id])
    if order && order.may_cancel?
      order.cancel!
      redirect_to orders_path, notice: "訂單已取消"
    else
      redirect_to orders_path, alert: "訂單無法取消"
    end
  end

  

  def create
    # 建立訂單

	    build_order

	  	if @order.save

	  	#刷卡
			  if payment.success?
		  	#清空購物車
		  	session[CART_SESSION] = nil
		  	#轉往首頁
		  		redirect_to root_path, notice: "感謝您"
		  	else 
		  		redirect_to root_path,alert: "失敗"
	  	end


	  end
	end

  private
  def order_params
  	params.require(:order).permit(:receipent, :tel, :address, :company_id)
  end

  private

  def payment
  	Braintree::Transaction.sale(
		  :amount => @cart.total_price,
		  :payment_method_nonce => params[:payment_method_nonce]
	)
  end

  def build_order
  	@order = current_user.orders.build(order_params)
    @cart.items.each do |item|
      @order.order_items.build(
        product: item.product,
        quantity: item.quantity,
        price: item.price
      )
    end
  end

end

app/views/orders/index.html.erb
<h1>訂單列表</h1>


 <table class="table">
 	<thead>
	 	<tr>
	 		<td>日期</td>
	 		<td>訂單編號</td>
	 		<td>金額</td>
	 		<td>狀態</td>
	 		<td>詳細資料</td>
	 	</tr>
 	</thead>
 	 	<tbody>
	 	<tr>
	 		<% @orders.each do |order| %>
	 		<td><%= order.created_at %></td>
	 		<td><%= order.serial %></td>
	 		<td><%= order.total_price %></td>
	 		<td><%= order.aasm_state %></td>
	 		<td><%= link_to '詳細', order, class: 'btn btn-xs btn-success' %>
	 			<%= link_to '取消', cancel_order_path(order), method: "delete", class: 'btn btn-xs btn-danger' if order.may_cancel? %>
	 		</td>
	 	</tr>
	 	<% end %>
 	</tbody>
 </table>

app/views/orders/show.html.erb
<h1>訂單明細</h1>

<%= @order.order_items %>