config/routes.rb
Rails.application.routes.draw do

  #加入認證
  post 'auth_user' => 'authentication#authenticate_user'

  apipie
  devise_for :users
  root "products#index"
  resources :products,  only: [:index, :show, :new, :create]

  resource :cart, only: [:show, :destroy] do
    post :add, path: '/add/:id'
    get :checkout
  end

  resources :orders, only: [:index, :show, :new, :create] do
	  	member do
	  	delete :cancel
	  end
  end
end

app/models/cart.rb
class Cart
  include Taxable

  attr_reader :items
  def initialize(items = [])
    @items = items
  end

  def empty?
    items.empty?
  end

  def add_item(product_id)
    found_item = items.find { |item| item.product_id == product_id }

    if found_item
      found_item.increment
    else
      items << CartItem.new(product_id)
    end
  end

  def total_price
    total = items.reduce(0) { |sum, item| sum + item.price }

    #聖誕節打9折
    if xmas
      total * 0.9
    else
      total
    end
  end

  def serialize
    result = items.map { |item| {"product_id" => item.product_id, "quantity" => item.quantity} }

    { "items" => result }
  end

  def self.from_hash(hash)
    if hash && hash["items"]
      new hash["items"].map { |item_hash|
        CartItem.new(item_hash["product_id"], item_hash["quantity"])
      }
    else
      new
    end
  end

  private
  def xmas
    Date.today.month == 12 && Date.today.day == 25
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

  before_action :user_only!, only: [:checkout]

  def add
    product = Product.find_by(id: params[:id])
    if product
      @cart.add_item(product.id)
      session[CART_SESSION] = @cart.serialize
      redirect_to root_path, notice: "已放至購物車"
    else
      redirect_to root_path, notice: "查無此商品"
    end
  end

  def show
  end

  def checkout
  end

  def destroy
    session[CART_SESSION] = nil
    redirect_to root_path, notice: "購物車已清除"
  end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_cart.html.erb
<table class="table">
  <thead>
    <tr>
      <td>商品項目</td>
      <td>單價</td>
      <td>數量</td>
      <td>小計</td>
    </tr>
  </thead>
  <tbody>
    <% cart.items.each do |item| %>
    <tr>
      <td><%= item.product.title %></td>
      <td><%= item.product.price %></td>
      <td><%= item.quantity %></td>
      <td><%= item.price %></td>
    </tr>
    <% end %>
  </tbody>
  <tfood>
    <tr>
      <td colspan="3" align="right">未稅價</td>
      <td><%= cart.total_price_without_tax %></td>
    </tr>
    <tr>
      <td colspan="3" align="right">5% 營業稅</td>
      <td><%= cart.tax %></td>
    </tr>
    <tr>
      <td colspan="3" align="right">總價</td>
      <td><%= cart.total_price %></td>
    </tr>
  </tfood>
</table>

app/views/carts/checkout.html.erb
<h1>結帳</h1>

<h2>購買明細</h2>
<%= render "cart", cart: @cart %>

<h2>收件人</h2>
<%= simple_form_for(Order.new) do |f| %>

	<div id="payment-form"></div>
	
  <%= f.input :receipent, label: false, placeholder:'收件人姓名' %>
  <%= f.input :tel, label: false, placeholder:'電話'  %>
  <%= f.input :address, label: false, placeholder:'地址'%>
  <%= f.input :company_id, label: false, placeholder:'公司統編' %>

  <hr>
	


  <%= f.submit "建立訂單", class:'btn btn-danger' %>
<% end %>

	

  <script src="https://js.braintreegateway.com/js/braintree-2.30.0.min.js"></script>
<script>
var clientToken = "<%= Braintree::ClientToken.generate %>"


braintree.setup(clientToken, "dropin", {
  container: "payment-form"
});
</script>

app/views/carts/show.html.erb
<h1>購物車內容</h1>
<%= link_to '清除購物車', cart_path, method: "delete", data: {confirm: "確定清除購物車?!"}, class:'btn btn-sm btn-danger' %>

<%= render "cart", cart: @cart %>

<%= link_to '繼續選購', root_path, class:'btn btn-default' %>
<%= link_to '結帳', checkout_cart_path, class:'btn btn-danger' unless @cart.empty? %>