config/routes.rb
Rails.application.routes.draw do

  #加入認證
  post 'auth_user' => 'authentication#authenticate_user'

  apipie
  devise_for :users
  root "products#index"
  resources :products,  only: [:index, :show, :new, :create]

  resource :cart, only: [:show, :destroy] do
    post :add, path: '/add/:id'
    get :checkout
  end

  resources :orders, only: [:index, :show, :new, :create] do
	  	member do
	  	delete :cancel
	  end
  end
end

app/models/product.rb
class Product < ApplicationRecord
	acts_as_paranoid
  has_many :order_items
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController



  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_request!

  # GET /products
  # GET /products.json
  def index
    @products = Product.page(params[:page]).per(6)
    render json: {'logged_in' => true}
    # render json: @products #這一行可以把 Products 所有資料輸出成 jaon 格式，並顯示出來
  end

  # GET /products/1
  # GET /products/1.json

  def show
  end

  # GET /products/new
  
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:title, :description, :price)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_for(product) do |f| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.label :price %>
    <%= f.number_field :price %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<h1>商品列表</h1>

<%= paginate @products, theme: 'twitter-bootstrap-3' %>

<div class="row">
  <% @products.each do |product| %>
  <!-- begin -->
  <div class="col-sm-6 col-md-4">
    <div class="thumbnail">
      <img src="http://fakeimg.pl/250x200/?text=<%=product.title%>">
      <div class="caption">
        <h3><%= product.title %></h3>
        <p>售價：<%= product.price %></p>
        <p><%= product.description.truncate(60) %></p>
        <p>
          <%= link_to '詳細資料', product, class:'btn btn-primary' %>
          <%= link_to '放到購物車', add_cart_path(product), class:'btn btn-danger', method: "post" %>
        </p>
      </div>
    </div>
  </div>
  <!-- end -->
  <% end %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @product.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>